spring:
  application:
    name: sm-system
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

# run 'openssl rand -base64 32' in git bash
jwt:
  secret:
    key: TBNJcHIfrjhS7dCALeQIiKg5gWTCZT7SjomGqWz5NRE=



